name = "open-lovable22"
compatibility_date = "2025-01-21"

# Pages build configuration
pages_build_output_dir = "out"

[build]
command = "npm run build"
output_directory = "out"

[env.production]
name = "open-lovable22"

[env.preview]
name = "open-lovable22-preview"