name = "open-lovable22"
compatibility_date = "2025-01-21"

[build]
command = "npm run build"
output_directory = "out"

[env.production]
name = "open-lovable22"

[env.preview]
name = "open-lovable22-preview"

# Pages configuration
[pages]
# Enable Pages Functions if needed
# functions_dir = "functions"

# Environment variables (if needed)
# [env.production.vars]
# API_URL = "https://api.example.com"

# [env.preview.vars]
# API_URL = "https://staging-api.example.com"