name = "open-lovablew"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2025-01-21"

# Pages build configuration (keep for Pages integration)
pages_build_output_dir = "out"