name = "open-lovablew"
compatibility_date = "2025-01-21"
# When using next-on-pages, Pages will publish from .vercel/output/static
# but wrangler.toml can omit pages_build_output_dir; Pages settings will use
# the build output automatically.