# Cloudflare Pages configuration for open-lovable Next.js app
name = "open-lovable"
compatibility_date = "2024-12-19"

[env.production]
compatibility_date = "2024-12-19"

[env.preview]
compatibility_date = "2024-12-19"

# Build configuration
[build]
command = "npm run build:cf"
cwd = "."

# Environment variables (add your actual values in Cloudflare dashboard)
[vars]
NODE_ENV = "production"

# For sensitive variables like API keys, use the Cloudflare dashboard:
# - GROQ_API_KEY
# - ANTHROPIC_API_KEY  
# - OPENAI_API_KEY
# - E2B_API_KEY
# - ANTHROPIC_BASE_URL
# - OPENAI_BASE_URL

# Pages configuration
[pages]
# Compatibility flags for Next.js with Cloudflare Pages
compatibility_flags = ["nodejs_compat"]

# Function invocation routes (matches your API routes)
[[pages.functions]]
pattern = "/api/*"
zone = "automatic"